<?php

namespace App\Services;

use FPDF;

class VoucherPDF extends FPDF
{
    public function __construct($orientation = 'P', $unit = 'mm', $size = 'A4')
    {
        parent::__construct($orientation, $unit, $size);

        $this->SetMargins(0, 0, 0);
        $this->SetAutoPageBreak(false);

        // Default black
        $this->SetTextColor(0, 0, 0);
        $this->SetDrawColor(0, 0, 0);
    }

    public function Header()
    {
        // No global header
    }

    public function drawDivider($x)
    {
        // Voucher borders already separate the copies cleanly.
    }

    public function renderVoucher($title, $x, $data)
    {
        $width = 90;
        $startY = 12;
        $innerX = $x + 4;
        $innerW = $width - 8;
        $bottomY = $startY + 185;

        $this->SetLineWidth(0.3);
        $this->Rect($x, $startY, $width, 185);

        $this->drawHeader($title, $x, $startY, $width, $innerX, $data);

        $y = $startY + 32;
        $this->drawStudentPanel($innerX, $y, $innerW, $data);

        $y += 40;
        $total = $this->drawFeeTable($innerX, $y, $data['fees'] ?? []);
        $y = $this->GetY() + 2;

        $this->drawTotalBand($innerX, $y, $innerW, $total);

        $y += 14;
        $this->drawDueDatePanel($innerX, $y, $innerW, $data);

        $signatureY = max($y + 24, $bottomY - 28);
        $this->drawSignatures($innerX, $signatureY);

        $this->SetFont('Arial', '', 6.5);
        $this->SetXY($innerX, $bottomY - 6);
        $this->Cell($innerW, 4, 'Generated by School Fee Management System', 0, 0, 'C');
    }

    private function drawHeader($title, $x, $startY, $width, $innerX, $data)
    {
        // Border only header
        $this->Rect($x, $startY, $width, 30);

        $this->SetFont('Arial', 'B', 9);
        $this->SetXY($innerX, $startY + 3);
        $this->Cell(50, 5, strtoupper($title), 0, 0, 'L');

        $this->SetFont('Arial', '', 8);
        $this->SetXY($x + 50, $startY + 3);
        $this->Cell(32, 5, 'FEE VOUCHER', 0, 0, 'R');

        // Logo (optional)
        $logoPath = public_path('images/usindh_logo.png');
        if (is_file($logoPath)) {
            $this->Rect($innerX, $startY + 10, 16, 16);
            $this->Image($logoPath, $innerX + 2, $startY + 11.5, 12);
        }

        $this->SetFont('Arial', 'B', 10);
        $this->SetXY($x + 24, $startY + 11);
        $this->MultiCell(60, 5, strtoupper($this->value($data, 'school_name')), 0, 'L');

        $this->SetFont('Arial', '', 7);
        $this->SetXY($x + 24, $startY + 22);
        $this->Cell(60, 4, 'Monthly fee collection slip', 0, 0, 'L');
    }

    private function drawStudentPanel($x, $y, $width, $data)
    {
        $rows = [
            ['Student', $this->value($data, 'student_name')],
            ['Father', $this->value($data, 'father_name')],
            ['Class', $this->value($data, 'class')],
            ['Fee Month', $this->value($data, 'fee_month')],
        ];

        $labelW = 28;
        $valueW = $width - $labelW;
        $rowH = 8;

        foreach ($rows as $index => [$label, $value]) {
            $this->SetXY($x, $y + ($index * $rowH));

            $this->SetFont('Arial', 'B', 7.5);
            $this->Cell($labelW, $rowH, strtoupper($label), 1);

            $this->SetFont('Arial', 'B', 8.5);
            $this->Cell($valueW, $rowH, $this->truncate($value, 34), 1);
        }
    }

    private function drawFeeTable($x, $y, $fees)
    {
        $this->SetFont('Arial', 'B', 9);
        $this->SetXY($x, $y);
        $this->Cell(52, 7, 'Fee Description', 1);
        $this->Cell(30, 7, 'Amount', 1, 1, 'R');

        $total = 0;

        foreach ($fees as $fee) {
            $amount = (float) ($fee['amount'] ?? 0);

            $this->SetFont('Arial', '', 9);
            $this->SetX($x);
            $this->Cell(52, 6, $this->truncate($fee['name'] ?? '', 28), 1);

            $this->SetFont('Arial', 'B', 9);
            $this->Cell(30, 6, 'Rs. ' . number_format($amount, 2), 1, 1, 'R');

            $total += $amount;
        }

        if (empty($fees)) {
            $this->SetFont('Arial', '', 8);
            $this->SetX($x);
            $this->Cell(82, 8, 'No fee items added', 1, 1, 'C');
        }

        return $total;
    }

    private function drawTotalBand($x, $y, $width, $total)
    {
        $this->Rect($x, $y, $width, 10);

        $this->SetFont('Arial', 'B', 10);
        $this->SetXY($x + 3, $y + 2);
        $this->Cell(40, 5, 'TOTAL PAYABLE');

        $this->SetXY($x + 40, $y + 2);
        $this->Cell(36, 5, 'Rs. ' . number_format($total, 2), 0, 0, 'R');
    }

    private function drawDueDatePanel($x, $y, $width, $data)
    {
        $this->Rect($x, $y, $width, 16);

        $this->SetFont('Arial', 'B', 8);
        $this->SetXY($x + 3, $y + 2);
        $this->Cell(30, 4, 'DUE DATE');

        $this->SetFont('Arial', 'B', 10);
        $this->SetXY($x + 3, $y + 7);
        $this->Cell(40, 5, $this->value($data, 'due_date'));

        $this->SetFont('Arial', '', 7);
        $this->SetXY($x + 42, $y + 3);
        $this->MultiCell(35, 4, 'Please retain this copy after payment.');
    }

    private function drawSignatures($x, $y)
    {
        $this->Line($x + 2, $y, $x + 34, $y);
        $this->Line($x + 48, $y, $x + 80, $y);

        $this->SetFont('Arial', '', 7);
        $this->SetXY($x + 2, $y + 2);
        $this->Cell(32, 4, 'Parent Sign', 0, 0, 'C');

        $this->SetXY($x + 48, $y + 2);
        $this->Cell(32, 4, 'Authorized Sign', 0, 0, 'C');
    }

    private function value($data, $key)
    {
        return isset($data[$key]) && $data[$key] !== '' ? (string) $data[$key] : '-';
    }

    private function truncate($value, $length)
    {
        $value = trim((string) $value);

        if (strlen($value) <= $length) {
            return $value;
        }

        return substr($value, 0, $length - 3) . '...';
    }
}