<?php

namespace App\Services;

use FPDF;

class VoucherPDF extends FPDF
{
    private const BRAND = [30, 87, 153];
    private const BRAND_DARK = [20, 57, 105];
    private const ACCENT = [238, 168, 47];
    private const INK = [38, 48, 66];
    private const MUTED = [101, 116, 139];
    private const LINE = [206, 214, 225];
    private const SOFT = [243, 247, 252];

    public function __construct($orientation = 'P', $unit = 'mm', $size = 'A4')
    {
        parent::__construct($orientation, $unit, $size);

        $this->SetMargins(0, 0, 0);
        $this->SetAutoPageBreak(false);
    }

    public function Header()
    {
        // No global header.
    }

    public function drawDivider($x)
    {
        // Voucher borders already separate the copies cleanly.
    }

    public function renderVoucher($title, $x, $data)
    {
        $width = 90;
        $startY = 12;
        $innerX = $x + 4;
        $innerW = $width - 8;
        $bottomY = $startY + 185;

        $this->setRgb('LINE', 'draw');
        $this->SetLineWidth(0.35);
        $this->Rect($x, $startY, $width, 185);

        $this->drawHeader($title, $x, $startY, $width, $innerX, $data);

        $y = $startY + 36;
        $this->drawStudentPanel($innerX, $y, $innerW, $data);

        $y += 41;
        $total = $this->drawFeeTable($innerX, $y, $data['fees'] ?? []);
        $y = $this->GetY() + 2;

        $this->drawTotalBand($innerX, $y, $innerW, $total);

        $y += 18;
        $this->drawDueDatePanel($innerX, $y, $innerW, $data);

        $signatureY = max($y + 26, $bottomY - 31);
        $this->drawSignatures($innerX, $signatureY);

        $this->setRgb('MUTED', 'text');
        $this->SetFont('Arial', '', 6.5);
        $this->SetXY($innerX, $bottomY - 7);
        $this->Cell($innerW, 4, 'Generated by School Fee Management System', 0, 0, 'C');
    }

    private function drawHeader($title, $x, $startY, $width, $innerX, $data)
    {
        $this->setRgb('BRAND', 'fill');
        $this->Rect($x, $startY, $width, 30, 'F');
        $this->setRgb('BRAND_DARK', 'fill');
        $this->Rect($x, $startY, $width, 8, 'F');

        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial', 'B', 8);
        $this->SetXY($innerX, $startY + 1.6);
        $this->Cell(38, 4, strtoupper($title), 0, 0, 'L');

        $this->SetFont('Arial', '', 7);
        $this->SetXY($x + 54, $startY + 1.6);
        $this->Cell(32, 4, 'FEE VOUCHER', 0, 0, 'R');

        $logoPath = public_path('images/usindh_logo.png');
        if (is_file($logoPath)) {
            $this->SetFillColor(255, 255, 255);
            $this->Rect($innerX, $startY + 11, 16, 16, 'F');
            $this->Image($logoPath, $innerX + 2, $startY + 12.5, 12);
        }

        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial', 'B', 11);
        $this->SetXY($x + 24, $startY + 12);
        $this->MultiCell(60, 4.8, strtoupper($this->value($data, 'school_name')), 0, 'L');

        $this->SetFont('Arial', '', 7);
        $this->SetXY($x + 24, $startY + 23);
        $this->Cell(60, 4, 'Monthly fee collection slip', 0, 0, 'L');
    }

    private function drawStudentPanel($x, $y, $width, $data)
    {
        $rows = [
            ['Student', $this->value($data, 'student_name')],
            ['Father', $this->value($data, 'father_name')],
            ['Class', $this->value($data, 'class')],
            ['Fee Month', $this->value($data, 'fee_month')],
        ];

        $labelW = 28;
        $valueW = $width - $labelW;
        $rowH = 8;

        foreach ($rows as $index => [$label, $value]) {
            $fill = $index % 2 === 0;

            if ($fill) {
                $this->SetFillColor(248, 250, 253);
            }

            $this->setRgb('LINE', 'draw');
            $this->SetXY($x, $y + ($index * $rowH));

            $this->setRgb('MUTED', 'text');
            $this->SetFont('Arial', 'B', 7.5);
            $this->Cell($labelW, $rowH, strtoupper($label), 1, 0, 'L', $fill);

            $this->setRgb('INK', 'text');
            $this->SetFont('Arial', 'B', 8.5);
            $this->Cell($valueW, $rowH, $this->truncate($value, 34), 1, 0, 'L', $fill);
        }
    }

    private function drawFeeTable($x, $y, $fees)
    {
        $this->setRgb('BRAND_DARK', 'fill');
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial', 'B', 9);
        $this->SetXY($x, $y);
        $this->Cell(52, 7, 'Fee Description', 1, 0, 'L', true);
        $this->Cell(30, 7, 'Amount', 1, 1, 'R', true);

        $total = 0;
        $rowIndex = 0;

        foreach ($fees as $fee) {
            $amount = (float) ($fee['amount'] ?? 0);
            $fill = $rowIndex % 2 === 0;

            if ($fill) {
                $this->SetFillColor(248, 250, 253);
            }

            $this->setRgb('LINE', 'draw');
            $this->setRgb('INK', 'text');
            $this->SetFont('Arial', '', 9);
            $this->SetX($x);
            $this->Cell(52, 6, $this->truncate($fee['name'] ?? '', 28), 1, 0, 'L', $fill);
            $this->SetFont('Arial', 'B', 9);
            $this->Cell(30, 6, 'Rs. ' . number_format($amount, 2), 1, 1, 'R', $fill);

            $total += $amount;
            $rowIndex++;
        }

        if ($rowIndex === 0) {
            $this->setRgb('LINE', 'draw');
            $this->setRgb('MUTED', 'text');
            $this->SetFont('Arial', '', 8);
            $this->SetX($x);
            $this->Cell(82, 8, 'No fee items added', 1, 1, 'C');
        }

        return $total;
    }

    private function drawTotalBand($x, $y, $width, $total)
    {
        $this->setRgb('ACCENT', 'fill');
        $this->setRgb('ACCENT', 'draw');
        $this->Rect($x, $y, $width, 12, 'DF');

        $this->setRgb('INK', 'text');
        $this->SetFont('Arial', 'B', 10);
        $this->SetXY($x + 3, $y + 2.8);
        $this->Cell(35, 5, 'TOTAL PAYABLE', 0, 0, 'L');
        $this->SetXY($x + 43, $y + 2.8);
        $this->Cell(36, 5, 'Rs. ' . number_format($total, 2), 0, 0, 'R');
    }

    private function drawDueDatePanel($x, $y, $width, $data)
    {
        $this->setRgb('SOFT', 'fill');
        $this->setRgb('LINE', 'draw');
        $this->Rect($x, $y, $width, 18, 'DF');

        $this->setRgb('MUTED', 'text');
        $this->SetFont('Arial', 'B', 7);
        $this->SetXY($x + 3, $y + 3);
        $this->Cell(28, 4, 'DUE DATE', 0, 0, 'L');

        $this->setRgb('BRAND_DARK', 'text');
        $this->SetFont('Arial', 'B', 11);
        $this->SetXY($x + 3, $y + 8);
        $this->Cell(35, 6, $this->value($data, 'due_date'), 0, 0, 'L');

        $this->setRgb('MUTED', 'text');
        $this->SetFont('Arial', '', 7);
        $this->SetXY($x + 41, $y + 4);
        $this->MultiCell(38, 4, 'Please retain this copy after payment for your records.', 0, 'L');
    }

    private function drawSignatures($x, $y)
    {
        $this->setRgb('LINE', 'draw');
        $this->Line($x + 2, $y, $x + 34, $y);
        $this->Line($x + 48, $y, $x + 80, $y);

        $this->setRgb('INK', 'text');
        $this->SetFont('Arial', '', 7);
        $this->SetXY($x + 2, $y + 2);
        $this->Cell(32, 4, 'Parent Sign', 0, 0, 'C');
        $this->SetXY($x + 48, $y + 2);
        $this->Cell(32, 4, 'Authorized Sign', 0, 0, 'C');
    }

    private function value($data, $key)
    {
        return isset($data[$key]) && $data[$key] !== '' ? (string) $data[$key] : '-';
    }

    private function truncate($value, $length)
    {
        $value = trim((string) $value);

        if (strlen($value) <= $length) {
            return $value;
        }

        return substr($value, 0, $length - 3) . '...';
    }

    private function setRgb($name, $target)
    {
        [$r, $g, $b] = constant("self::$name");

        if ($target === 'fill') {
            $this->SetFillColor($r, $g, $b);
            return;
        }

        if ($target === 'draw') {
            $this->SetDrawColor($r, $g, $b);
            return;
        }

        $this->SetTextColor($r, $g, $b);
    }
}
